version: "3"

services:
  openvpn-as:
    image: linuxserver/openvpn-as:2.7.4-ls21
    container_name: openvpn-as
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ./data/config:/config
    ports:
      - 943:943
      - 9443:8443
    restart: always
